name: build
on: [push]
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: G++ install
        shell: bash
        run: |
         sudo apt-get remove g++-9
         sudo apt install g++-11
         sudo mv /usr/bin/g++-11 /usr/bin/g++
         whereis g++
      - name: Build
        shell: bash
        run: make
      - name: Upload build
        uses: actions/upload-artifact@v3.1.0
        with:
         name: hexagn
         path: ./hexagn
         retention-days: 90
      - name: Upload libs
        uses: actions/upload-artifact@v3.1.0
        with:
         name: libs
         path: ./hexagn-stdlib/
         retention-days: 90
